version: '3'
services:
  redis:
    image: redis:3.2
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  postgres:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  superset:
    image: guavus-superset
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # If using production, comment development volume below
      #SUPERSET_ENV: production
      SUPERSET_ENV: development
    ports:
      - 8088:8088
    depends_on:
      - postgres
      - redis
    volumes:
      - superset-node-modules:/home/work/incubator-superset/superset/assets/node_modules
volumes:
  postgres:
    external: false
  redis:
    external: false
