---

- name: Retrieve facts all host
  hosts:
    - all
  gather_facts: true
  any_errors_fatal: true
  tags:
    - 'always'
  tasks: []


- name: "Set superset psql host IP"
  hosts:
    - management-nodes
  tags:
    - always
  tasks:
    - set_fact:
        site_floating_ip:
          ip: "{{ hostvars[groups['management-nodes'][0]]['ansible_default_ipv4']['address'] }}"
      when: site_deployment_type == 'NONHA'

# This play permits to use a hierarchy of variables. The
# variables are loaded form the vars inventory dir. It
# respects the following order:
#  - common
#  - customers/common
#  - customers/stage
#  - extra_vars
- name: Load hierarchical variables
  hosts:
    - all
  any_errors_fatal: True
  tags:
    - 'always'
  roles:
    - reflex-provisionner/load_vars


- name: Superset db creation
  hosts:
    - management-nodes
  roles:
    - role: raf/superset/data_model


- name: Superset role deployment
  hosts:
    - management-nodes
  roles:
    - raf/superset/superset